In [12]:
import pandas as pd

In [13]:
df = pd.read_csv('Test_sorted.csv')

In [14]:
df.head(5)

,East_Midlands_price,Eastern_England_price,London_price,Merseyside_and_Northern_Wales_price,North_Western_England_price,Northern_Scotland_price,South_Western_England_price,Southern_England_price,Southern_Scotland_price,West_Midlands_price,...,windspeed_100mSouthhampton - Portsmouth_weather,winddirection_10mSouthhampton - Portsmouth_weather,winddirection_100mSouthhampton - Portsmouth_weather,windgusts_10mSouthhampton - Portsmouth_weather,populationSouthhampton - Portsmouth_weather,latitudeSouthhampton - Portsmouth_weather,longitudeSouthhampton - Portsmouth_weather,generationtime_msSouthhampton - Portsmouth_weather,utc_offset_secondsSouthhampton - Portsmouth_weather,elevationSouthhampton - Portsmouth_weather
0,35.071785,37.717785,35.797230,40.363785,37.717785,45.655785,43.009785,37.717785,37.717785,37.717785,...,23.5,54.0,49.0,22.7,927916.0,50.699997,-1.199997,61.430931,0.0,10.0
1,38.851785,41.686785,38.851785,44.521785,41.686785,50.191785,47.356785,41.686785,41.686785,41.686785,...,27.4,54.0,252.0,22.3,927916.0,50.699997,-1.199997,61.430931,0.0,10.0
2,35.533785,38.200785,35.797230,40.867785,38.200785,46.212285,43.545285,38.200785,38.200785,38.200785,...,23.4,49.0,43.0,22.3,927916.0,50.699997,-1.199997,61.430931,0.0,10.0
3,33.874785,36.457785,35.797230,39.051285,36.457785,44.217285,41.634285,36.457785,36.457785,36.457785,...,27.4,54.0,252.0,22.3,927916.0,50.699997,-1.199997,61.430931,0.0,10.0
4,33.018090,35.056875,35.797230,36.940785,34.452285,41.928285,39.439785,34.452285,34.452285,34.452285,...,23.4,51.0,44.0,21.6,927916.0,50.699997,-1.199997,61.430931,0.0,10.0

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9888 entries, 0 to 9887
Columns: 251 entries, East_Midlands_price to elevationSouthhampton - Portsmouth_weather
dtypes: float64(251)
memory usage: 18.9 MB

In [16]:
df.isna()

,East_Midlands_price,Eastern_England_price,London_price,Merseyside_and_Northern_Wales_price,North_Western_England_price,Northern_Scotland_price,South_Western_England_price,Southern_England_price,Southern_Scotland_price,West_Midlands_price,...,windspeed_100mSouthhampton - Portsmouth_weather,winddirection_10mSouthhampton - Portsmouth_weather,winddirection_100mSouthhampton - Portsmouth_weather,windgusts_10mSouthhampton - Portsmouth_weather,populationSouthhampton - Portsmouth_weather,latitudeSouthhampton - Portsmouth_weather,longitudeSouthhampton - Portsmouth_weather,generationtime_msSouthhampton - Portsmouth_weather,utc_offset_secondsSouthhampton - Portsmouth_weather,elevationSouthhampton - Portsmouth_weather
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9883,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9884,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9885,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9886,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9887,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False